### ISSUE TITLE
error with account exemple get_all_transactions.py 

### ISSUE THREAD

**Issue by carabine** [corpetty/py-etherscan-api#14]
I tried this address : '0xfbb1b73c4f0bda4f67dca266ce6ef42f520fbb98' , it took a while, then I got this error : 

Traceback (most recent call last):
  File "get_all_transactions.py", line 13, in <module>
    transactions = api.get_all_transactions(offset=10000, sort='asc', internal=True)
  File "/usr/lib/python3.6/site-packages/etherscan/accounts.py", line 84, in get_all_transactions
    trans_list += req['result']
TypeError: 'NoneType' object is not iterable

thanks for the work

**Comment by corpetty** [comment]
Recent merge from @taylorjdawson should fix this.
