### ISSUE TITLE
ValueError: expected parenthesized list: '==2.18.4'

### ISSUE THREAD

**Issue by AndreMiras** [corpetty/py-etherscan-api#27]
```
$ pip install https://github.com/corpetty/py-etherscan-api/archive/f45a313.zip#egg=py-etherscan-api
Collecting py-etherscan-api from https://github.com/corpetty/py-etherscan-api/archive/f45a313.zip#egg=py-etherscan-api
  Downloading https://github.com/corpetty/py-etherscan-api/archive/f45a313.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jilk_tj9/py-etherscan-api/setup.py", line 13, in <module>
        'requests==2.18.4',
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/andre/workspace/py-etherscan-api/venv/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 253, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/lib/python3.6/distutils/dist.py", line 1207, in set_requires
        distutils.versionpredicate.VersionPredicate(v)
      File "/usr/lib/python3.6/distutils/versionpredicate.py", line 114, in __init__
        raise ValueError("expected parenthesized list: %r" % paren)
    ValueError: expected parenthesized list: '==2.18.4'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jilk_tj9/py-etherscan-api/
```

This is because we should use `install_requires` rather than `requires` in `setup.py`, I'll provide a pull request.

**Comment by AndreMiras** [comment]
Here's the pull request that fixes it https://github.com/corpetty/py-etherscan-api/pull/28
