### ISSUE TITLE
setup script doesnt work on python3.6

### ISSUE THREAD

**Issue by chppppp** [corpetty/py-etherscan-api#85]
i run `python3 setup.py install` and then

```
asdasd@frickyou:~/etherscan$ python3 etherscan.py 
Traceback (most recent call last):
  File "etherscan.py", line 1, in <module>
    from etherscan.contracts import Contract
  File "/home/asdasd/etherscan/etherscan.py", line 1, in <module>
    from etherscan.contracts import Contract
ModuleNotFoundError: No module named 'etherscan.contracts'; 'etherscan' is not a package
```

**Comment by chppppp** [comment]
apparently you have to work within the folder, the pip package doesnt actually install globally or something.

**Comment by pcko1** [comment]
try `pip install .` @chppppp
